// Copyright 2024-2026 Jonathan Shook
// SPDX-License-Identifier: Apache-2.0

//! Framing markdown report — bundles summary tables and plot
//! images into a single `summary.md` (or user-named) file
//! that lives next to the metrics db. `nbrs summary` and
//! `nbrs plot` both append into this doc by default, so a
//! finished session ends up with one navigable artifact
//! covering every named summary and every named plot.
//!
//! ## File structure
//!
//! Each artifact lives under a level-2 heading whose text is
//! a structured anchor:
//!
//! ```markdown
//! # nb-rs session report
//!
//! _Generated by `nbrs summary` / `nbrs plot`._
//!
//! ## summary: recallnmore
//!
//! | Activity | Cycles | … |
//! | --- | --- | --- |
//! | … | … | … |
//!
//! ## plot: recall_at_k10
//!
//! ![recall_at_k10](plot_recall_at_k10.png)
//! ```
//!
//! ## Append vs replace
//!
//! [`upsert_section`] is idempotent: if a heading with the same
//! anchor already exists in the file, its body is replaced;
//! otherwise the section is appended. Re-running `nbrs summary
//! all` or `nbrs plot all` over the same db keeps the doc in
//! sync without growing duplicate sections.
//!
//! ## Path resolution
//!
//! Both commands accept `--report <path>` to override. With no
//! flag, the default is `<db_dir>/summary.md` — same directory
//! as the metrics db, named `summary.md`. The runner already
//! writes a per-summary `<name>_summary.md` for each named
//! summary; this companion bundles every artifact into one.

use std::path::Path;

const DOC_HEADER: &str = "# nb-rs session report\n\n\
    _Generated by `nbrs summary` / `nbrs plot`. Sections are\n\
    upserted by name — re-running these commands updates each\n\
    section in place rather than appending duplicates._\n\n";

/// How an existing same-name section is handled when writing
/// into a markdown report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteMode {
    /// `--update-markdown`: replace existing section in place,
    /// preserving its position. New sections are appended.
    /// Position-stable, content-fresh.
    Update,
    /// `--add-to-markdown`: append only when no section by the
    /// same anchor exists. Existing sections are left untouched
    /// (the new figure is *not* added). Use for "I want to
    /// build up a doc and never lose its contents".
    AddIfMissing,
}

/// Append or replace a section under the given anchor heading.
/// Returns whether the file was modified — `false` for
/// `AddIfMissing` mode when the section already existed.
pub fn write_section(
    report_path: &Path,
    anchor: &str,
    body: &str,
    mode: WriteMode,
) -> Result<bool, String> {
    let mut current = if report_path.exists() {
        std::fs::read_to_string(report_path)
            .map_err(|e| format!("read '{}': {e}", report_path.display()))?
    } else {
        DOC_HEADER.to_string()
    };
    if !current.starts_with("# ") {
        // File exists but doesn't look like our report; preserve
        // the user's existing content and append our header
        // before our sections so we don't clobber.
        current = format!("{DOC_HEADER}{current}");
    }

    let heading = format!("## {anchor}\n");
    let body_trimmed = body.trim_end_matches('\n');
    let new_section = format!("{heading}\n{body_trimmed}\n\n");

    let (updated, modified) = match (find_section(&current, &heading), mode) {
        (Some((start, end)), WriteMode::Update) => {
            // Replace existing section in place — position
            // preserved, content refreshed.
            let mut out = String::with_capacity(current.len() + new_section.len());
            out.push_str(&current[..start]);
            out.push_str(&new_section);
            out.push_str(&current[end..]);
            (out, true)
        }
        (Some(_), WriteMode::AddIfMissing) => {
            // Section already present — leave the file alone.
            (current, false)
        }
        (None, _) => {
            // Append. Ensure exactly one trailing blank line
            // before our new section.
            let mut prefix = current;
            while prefix.ends_with("\n\n\n") {
                prefix.pop();
            }
            if !prefix.ends_with("\n\n") {
                prefix.push('\n');
                if !prefix.ends_with("\n\n") { prefix.push('\n'); }
            }
            (format!("{prefix}{new_section}"), true)
        }
    };

    if !modified {
        return Ok(false);
    }

    if let Some(parent) = report_path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create dir '{}': {e}", parent.display()))?;
        }
    }
    std::fs::write(report_path, updated)
        .map_err(|e| format!("write '{}': {e}", report_path.display()))?;
    Ok(true)
}

/// Locate `[start_byte, end_byte)` of the existing section under
/// `heading`. End is the byte where the next `## ` heading
/// starts, or end-of-file. Returns `None` if not found.
fn find_section(text: &str, heading: &str) -> Option<(usize, usize)> {
    // Heading must start at line beginning. Search anchored.
    let pattern = heading;
    let mut start_byte: Option<usize> = None;
    for (idx, _) in text.match_indices(pattern) {
        let at_line_start = idx == 0 || text.as_bytes()[idx - 1] == b'\n';
        if at_line_start {
            start_byte = Some(idx);
            break;
        }
    }
    let start_byte = start_byte?;
    // End: find next `\n## ` at line start after `start_byte +
    // pattern.len()`.
    let after = &text[start_byte + pattern.len()..];
    let mut end_byte = text.len();
    for (rel, _) in after.match_indices("\n## ") {
        end_byte = start_byte + pattern.len() + rel + 1; // +1 to land on the `#` of next heading
        break;
    }
    Some((start_byte, end_byte))
}

/// Build a markdown image reference for a plot file. Uses the
/// file name as the alt text and a path relative to `report_path`
/// when both share a parent — otherwise the absolute path so
/// the doc resolves regardless of where it's opened from.
pub fn image_section_body(report_path: &Path, image_path: &Path) -> String {
    let rel = match (report_path.parent(), image_path) {
        (Some(parent), p) if parent == p.parent().unwrap_or(parent) => {
            p.file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_else(|| p.to_string_lossy().into_owned())
        }
        _ => image_path.to_string_lossy().into_owned(),
    };
    let alt = image_path.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "plot".into());
    format!("![{alt}]({rel})\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_path(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("nbrs_report_test_{}",
            std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join(name)
    }

    #[test]
    fn fresh_file_gets_doc_header() {
        let p = tmp_path("fresh.md");
        let _ = std::fs::remove_file(&p);
        upsert_section(&p, "summary: foo",
            "| col1 | col2 |\n| --- | --- |\n| a | b |").unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.starts_with("# nb-rs session report"));
        assert!(content.contains("## summary: foo"));
        assert!(content.contains("| a | b |"));
    }

    #[test]
    fn second_section_appends() {
        let p = tmp_path("appended.md");
        let _ = std::fs::remove_file(&p);
        upsert_section(&p, "summary: a", "table-a").unwrap();
        upsert_section(&p, "plot: b", "![](b.png)").unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("## summary: a"));
        assert!(content.contains("## plot: b"));
        assert!(content.find("## summary: a").unwrap()
            < content.find("## plot: b").unwrap());
    }

    #[test]
    fn rerun_replaces_section_in_place() {
        let p = tmp_path("replaced.md");
        let _ = std::fs::remove_file(&p);
        upsert_section(&p, "summary: a", "v1").unwrap();
        upsert_section(&p, "plot: b", "img-b").unwrap();
        upsert_section(&p, "summary: a", "v2-updated").unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("v2-updated"));
        assert!(!content.contains("v1\n"));
        // Order preserved
        assert!(content.find("## summary: a").unwrap()
            < content.find("## plot: b").unwrap());
    }

    #[test]
    fn add_if_missing_skips_existing_sections() {
        let p = tmp_path("add_only.md");
        let _ = std::fs::remove_file(&p);
        let modified_first = write_section(&p, "plot: a", "v1", WriteMode::AddIfMissing).unwrap();
        assert!(modified_first, "fresh section should be written");
        let modified_second = write_section(&p, "plot: a", "v2-IGNORED", WriteMode::AddIfMissing).unwrap();
        assert!(!modified_second, "second write should be skipped");
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("v1"), "v1 retained");
        assert!(!content.contains("v2-IGNORED"), "v2 was not written");
    }

    #[test]
    fn add_if_missing_appends_new_sections() {
        let p = tmp_path("add_new.md");
        let _ = std::fs::remove_file(&p);
        write_section(&p, "summary: a", "first", WriteMode::AddIfMissing).unwrap();
        // Add a different anchor — should append, not skip.
        let modified = write_section(&p, "plot: b", "second", WriteMode::AddIfMissing).unwrap();
        assert!(modified);
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("## summary: a"));
        assert!(content.contains("## plot: b"));
        assert!(content.contains("first"));
        assert!(content.contains("second"));
    }

    #[test]
    fn image_body_uses_relative_path_when_colocated() {
        let report = std::path::Path::new("/tmp/sess/summary.md");
        let img = std::path::Path::new("/tmp/sess/plot_recall.png");
        let body = image_section_body(report, img);
        assert!(body.contains("![plot_recall](plot_recall.png)"),
            "got: {body}");
    }
}
