// Copyright 2024-2026 Jonathan Shook
// SPDX-License-Identifier: Apache-2.0

//! Framing markdown report — bundles summary tables and plot
//! images into a single `summary.md` (or user-named) file
//! that lives next to the metrics db. `nbrs summary` and
//! `nbrs plot` both append into this doc by default, so a
//! finished session ends up with one navigable artifact
//! covering every named summary and every named plot.
//!
//! ## File structure
//!
//! Each artifact lives under a level-2 heading whose text is
//! a structured anchor:
//!
//! ```markdown
//! # nb-rs session report
//!
//! _Generated by `nbrs summary` / `nbrs plot`._
//!
//! ## summary: recallnmore
//!
//! | Activity | Cycles | … |
//! | --- | --- | --- |
//! | … | … | … |
//!
//! ## plot: recall_at_k10
//!
//! ![recall_at_k10](plot_recall_at_k10.png)
//! ```
//!
//! ## Append vs replace
//!
//! [`upsert_section`] is idempotent: if a heading with the same
//! anchor already exists in the file, its body is replaced;
//! otherwise the section is appended. Re-running `nbrs summary
//! all` or `nbrs plot all` over the same db keeps the doc in
//! sync without growing duplicate sections.
//!
//! ## Path resolution
//!
//! Both commands accept `--report <path>` to override. With no
//! flag, the default is `<db_dir>/summary.md` — same directory
//! as the metrics db, named `summary.md`. The runner already
//! writes a per-summary `<name>_summary.md` for each named
//! summary; this companion bundles every artifact into one.

use std::path::Path;

const DOC_HEADER: &str = "# nb-rs session report\n\n\
    _Generated by `nbrs summary` / `nbrs plot`. Sections are\n\
    upserted by name — re-running these commands updates each\n\
    section in place rather than appending duplicates._\n\n";

/// How an existing same-name section is handled when writing
/// into a markdown report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteMode {
    /// `--update-markdown`: replace existing section in place,
    /// preserving its position. New sections are appended.
    /// Position-stable, content-fresh.
    Update,
    /// `--add-to-markdown`: append only when no section by the
    /// same anchor exists. Existing sections are left untouched
    /// (the new figure is *not* added). Use for "I want to
    /// build up a doc and never lose its contents".
    AddIfMissing,
}

/// Write a SRD-46 named section: heading carries a display
/// string plus a stable `{#anchor}` token. The anchor is the
/// canonical item name; lookup ignores the display text so
/// reruns that change figure numbers / labels still find and
/// replace the prior section in place.
pub fn write_named_section(
    report_path: &Path,
    anchor: &str,
    heading_display: &str,
    body: &str,
    mode: WriteMode,
) -> Result<bool, String> {
    let mut current = if report_path.exists() {
        std::fs::read_to_string(report_path)
            .map_err(|e| format!("read '{}': {e}", report_path.display()))?
    } else {
        DOC_HEADER.to_string()
    };
    if !current.starts_with("# ") {
        current = format!("{DOC_HEADER}{current}");
    }

    let new_heading = format!("## {heading_display} {{#{anchor}}}\n");
    let body_trimmed = body.trim_end_matches('\n');
    let new_section = format!("{new_heading}\n{body_trimmed}\n\n");

    let (updated, modified) = match (find_section_by_anchor(&current, anchor), mode) {
        (Some((start, end)), WriteMode::Update) => {
            let mut out = String::with_capacity(current.len() + new_section.len());
            out.push_str(&current[..start]);
            out.push_str(&new_section);
            out.push_str(&current[end..]);
            (out, true)
        }
        (Some(_), WriteMode::AddIfMissing) => (current, false),
        (None, _) => {
            let mut prefix = current;
            while prefix.ends_with("\n\n\n") { prefix.pop(); }
            if !prefix.ends_with("\n\n") {
                prefix.push('\n');
                if !prefix.ends_with("\n\n") { prefix.push('\n'); }
            }
            (format!("{prefix}{new_section}"), true)
        }
    };

    if !modified { return Ok(false); }

    if let Some(parent) = report_path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create dir '{}': {e}", parent.display()))?;
        }
    }
    std::fs::write(report_path, updated)
        .map_err(|e| format!("write '{}': {e}", report_path.display()))?;
    Ok(true)
}

/// Like [`write_named_section`] but forces the section to be
/// the FIRST `##` heading in the file (right after the doc
/// header). Used for the auto-injected Details block (SRD-46)
/// so session context always reads at the top.
///
/// If the anchor already exists, its content is replaced in
/// place — same as [`write_named_section`]. If it doesn't
/// exist, the section is inserted directly after the doc
/// header line, before any existing `##` sections.
pub fn write_named_section_first(
    report_path: &Path,
    anchor: &str,
    heading_display: &str,
    body: &str,
) -> Result<bool, String> {
    let mut current = if report_path.exists() {
        std::fs::read_to_string(report_path)
            .map_err(|e| format!("read '{}': {e}", report_path.display()))?
    } else {
        DOC_HEADER.to_string()
    };
    if !current.starts_with("# ") {
        current = format!("{DOC_HEADER}{current}");
    }

    let new_heading = format!("## {heading_display} {{#{anchor}}}\n");
    let body_trimmed = body.trim_end_matches('\n');
    let new_section = format!("{new_heading}\n{body_trimmed}\n\n");

    let updated = if let Some((start, end)) = find_section_by_anchor(&current, anchor) {
        // Replace in place — preserves position whether or not
        // it's currently first.
        let mut out = String::with_capacity(current.len() + new_section.len());
        out.push_str(&current[..start]);
        out.push_str(&new_section);
        out.push_str(&current[end..]);
        out
    } else {
        // Insert after the first `# ` doc-header block (which
        // may span multiple lines until a blank line) and
        // before the first `## ` section.
        let insertion = current.find("\n## ")
            .map(|p| p + 1) // land on the `#` of the heading
            .or_else(|| current.find("\n# ").and_then(|_| {
                // no `## ` yet — append after the header
                // paragraph (look for the second `\n\n`)
                None
            }))
            .unwrap_or(current.len());
        // Step back to the start of any blank-line padding so
        // the new section is preceded by exactly one blank.
        let mut prefix = current[..insertion].to_string();
        let suffix = current[insertion..].to_string();
        while prefix.ends_with("\n\n\n") { prefix.pop(); }
        if !prefix.ends_with("\n\n") {
            prefix.push('\n');
            if !prefix.ends_with("\n\n") { prefix.push('\n'); }
        }
        format!("{prefix}{new_section}{suffix}")
    };

    if let Some(parent) = report_path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create dir '{}': {e}", parent.display()))?;
        }
    }
    std::fs::write(report_path, updated)
        .map_err(|e| format!("write '{}': {e}", report_path.display()))?;
    Ok(true)
}

/// Look up an existing `## … {#anchor}` heading by its anchor
/// token. End is the byte where the next `## ` heading starts,
/// or end-of-file.
fn find_section_by_anchor(text: &str, anchor: &str) -> Option<(usize, usize)> {
    let token = format!("{{#{anchor}}}");
    let mut start_byte: Option<usize> = None;
    for (idx, _) in text.match_indices(&token) {
        let line_start = text[..idx].rfind('\n').map(|p| p + 1).unwrap_or(0);
        if text[line_start..].starts_with("## ") {
            start_byte = Some(line_start);
            break;
        }
    }
    let start_byte = start_byte?;
    let after = &text[start_byte + 3..];
    let end_byte = after.find("\n## ")
        .map(|rel| start_byte + 3 + rel + 1)
        .unwrap_or(text.len());
    Some((start_byte, end_byte))
}

/// Pretty-print a snake_case canonical name as a heading-friendly
/// title. `recall_at_k10` → `Recall At K10`. Used as a fallback
/// when no `label "…"` directive was supplied.
pub fn prettify_name(name: &str) -> String {
    let mut out = String::new();
    let mut next_upper = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            out.push(' ');
            next_upper = true;
        } else if next_upper {
            out.extend(ch.to_uppercase());
            next_upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Build a markdown image reference for a plot file. Uses the
/// file name as the alt text and a path relative to `report_path`
/// when both share a parent — otherwise the absolute path so
/// the doc resolves regardless of where it's opened from.
pub fn image_section_body(report_path: &Path, image_path: &Path) -> String {
    let rel = match (report_path.parent(), image_path) {
        (Some(parent), p) if parent == p.parent().unwrap_or(parent) => {
            p.file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_else(|| p.to_string_lossy().into_owned())
        }
        _ => image_path.to_string_lossy().into_owned(),
    };
    let alt = image_path.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "plot".into());
    format!("![{alt}]({rel})\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_path(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("nbrs_report_test_{}",
            std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join(name)
    }

    #[test]
    fn add_if_missing_appends_new_sections() {
        let p = tmp_path("add_new.md");
        let _ = std::fs::remove_file(&p);
        let added = write_named_section(
            &p, "summary_a", "Summary A (table)", "first",
            WriteMode::AddIfMissing).unwrap();
        assert!(added);
        let added2 = write_named_section(
            &p, "plot_b", "Plot B (plot)", "second",
            WriteMode::AddIfMissing).unwrap();
        assert!(added2);
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("{#summary_a}"));
        assert!(content.contains("{#plot_b}"));
        assert!(content.contains("first"));
        assert!(content.contains("second"));
    }

    #[test]
    fn named_section_writes_anchor_and_kind() {
        let p = tmp_path("named.md");
        let _ = std::fs::remove_file(&p);
        write_named_section(&p, "recall_at_k10",
            "3. Recall At K10 (plot)",
            "![](plot_recall_at_k10.png)",
            WriteMode::Update).unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("## 3. Recall At K10 (plot) {#recall_at_k10}"),
            "heading missing: {content}");
    }

    #[test]
    fn named_section_relookup_by_anchor_survives_label_change() {
        let p = tmp_path("relookup.md");
        let _ = std::fs::remove_file(&p);
        write_named_section(&p, "recall_at_k10",
            "1. Recall At K10 (plot)", "first body",
            WriteMode::Update).unwrap();
        // Same anchor, different display heading + body. The
        // anchor-based lookup must still find and replace the
        // earlier section in place.
        write_named_section(&p, "recall_at_k10",
            "5. Recall@10 reordered (plot)", "second body",
            WriteMode::Update).unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(content.contains("5. Recall@10 reordered (plot) {#recall_at_k10}"),
            "new heading missing: {content}");
        assert!(content.contains("second body"), "new body missing: {content}");
        assert!(!content.contains("first body"), "stale body retained: {content}");
        // Exactly one heading for this anchor.
        assert_eq!(content.matches("{#recall_at_k10}").count(), 1);
    }

    #[test]
    fn prettify_simple() {
        assert_eq!(prettify_name("recall_at_k10"), "Recall At K10");
        assert_eq!(prettify_name("p99-latency"), "P99 Latency");
        assert_eq!(prettify_name("recall"), "Recall");
    }

    #[test]
    fn image_body_uses_relative_path_when_colocated() {
        let report = std::path::Path::new("/tmp/sess/summary.md");
        let img = std::path::Path::new("/tmp/sess/plot_recall.png");
        let body = image_section_body(report, img);
        assert!(body.contains("![plot_recall](plot_recall.png)"),
            "got: {body}");
    }
}
